### PR TITLE
Add page archiver

### PR DESCRIPTION
**Pull request by ondenman**
Archives scraped pages to github

### CODE REVIEW

**Review by tmtmtmtm — CHANGES_REQUESTED** [review]
screen shot 2016-09-28 at 09 08 31

**Comment by ondenman** [comment]
Updated repo description.

**Comment by ondenman** [comment]
⚠️ Morph environment needs to be configured

**Review by tmtmtmtm — APPROVED** [review]

**Comment by tmtmtmtm** [comment]
@ondenman this hasn't worked - https://morph.io/tmtmtmtm/guernsey-states

```
/app/vendor/bundle/ruby/2.0.0/gems/vcr-archive-0.3.0/lib/vcr/archive.rb:40:in `binread': No such file or directory - /tmp/cache/cedar-14/vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.6.2/dependencies.html (Errno::ENOENT)
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-archive-0.3.0/lib/vcr/archive.rb:40:in `block in []'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-archive-0.3.0/lib/vcr/archive.rb:38:in `map'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-archive-0.3.0/lib/vcr/archive.rb:38:in `[]'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:237:in `raw_cassette_bytes'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:181:in `previously_recorded_interactions'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:241:in `merged_interactions'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:256:in `interactions_to_record'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:118:in `serializable_hash'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:263:in `write_recorded_interactions_to_disk'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr/cassette.rb:65:in `eject'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr.rb:156:in `eject_cassette'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr.rb:191:in `ensure in use_cassette'
    from /app/vendor/bundle/ruby/2.0.0/gems/vcr-3.0.3/lib/vcr.rb:191:in `use_cassette'
    from /app/vendor/bundle/ruby/2.0.0/gems/scraped_page_archive-0.4.1/lib/scraped_page_archive.rb:29:in `record'
    from /app/vendor/bundle/ruby/2.0.0/gems/scraped_page_archive-0.4.1/lib/scraped_page_archive.rb:20:in `record'
    from /app/vendor/bundle/ruby/2.0.0/gems/scraped_page_archive-0.4.1/lib/scraped_page_archive/open-uri.rb:9:in `open_uri'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:689:in `open'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/open-uri.rb:34:in `open'
```

**Pull request merged**
